In [1]:
import urllib.request 
import time 
import pandas as pd

In [2]:
url1 = 'https://covid.ourworldindata.org/data/ecdc/total_cases.csv' #Uniform Resource Locator (URL)
filename1 = 'data/total_cases.csv'
print('Beginning file download ')
urllib.request.urlretrieve(url1, filename1)
time.sleep(.300) #delay for time 0.3 second

Beginning file download

In [3]:
url2 = 'https://covid.ourworldindata.org/data/ecdc/total_deaths.csv'
filename2 = 'data/total_deaths.csv'
print('Beginning file download ')
urllib.request.urlretrieve(url2, filename2)
time.sleep(.300)

Beginning file download

In [4]:
df1 = pd.read_csv(filename1)
df1

,date,World,Afghanistan,Albania,Algeria,Andorra,Angola,Anguilla,Antigua and Barbuda,Argentina,...,United States Virgin Islands,Uruguay,Uzbekistan,Vatican,Venezuela,Vietnam,Western Sahara,Yemen,Zambia,Zimbabwe
0,2019-12-31,27,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
1,2020-01-01,27,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
2,2020-01-02,27,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
3,2020-01-03,44,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
4,2020-01-04,44,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,2020-09-27,32920813,39227.0,13153.0,50914.0,1836.0,4590.0,3.0,101.0,702471.0,...,1317.0,1998.0,54953.0,12.0,71940.0,1069.0,766.0,2033.0,14612.0,7803.0
272,2020-09-28,33202820,39227.0,13259.0,51067.0,1836.0,4672.0,3.0,101.0,711312.0,...,1317.0,2008.0,55593.0,12.0,72691.0,1074.0,766.0,2034.0,14641.0,7812.0
273,2020-09-29,33436665,39239.0,13391.0,51213.0,1966.0,4797.0,3.0,101.0,723119.0,...,1318.0,2010.0,56068.0,12.0,73528.0,1077.0,766.0,2035.0,14660.0,7816.0
274,2020-09-30,33725618,39254.0,13518.0,51368.0,1966.0,4905.0,3.0,101.0,736596.0,...,1318.0,2033.0,56519.0,12.0,74363.0,1094.0,766.0,2035.0,14715.0,7837.0
275,2020-10-01,34029923,39268.0,13649.0,51530.0,2050.0,5013.0,3.0,101.0,750988.0,...,1318.0,2046.0,56997.0,12.0,75122.0,1094.0,766.0,2035.0,14759.0,7838.0

In [5]:
df2 = pd.read_csv(filename2)
df2

,date,World,Afghanistan,Albania,Algeria,Andorra,Angola,Anguilla,Antigua and Barbuda,Argentina,...,United States Virgin Islands,Uruguay,Uzbekistan,Vatican,Venezuela,Vietnam,Western Sahara,Yemen,Zambia,Zimbabwe
0,2019-12-31,0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
1,2020-01-01,0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
2,2020-01-02,0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
3,2020-01-03,0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
4,2020-01-04,0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,2020-09-27,995163,1453.0,375.0,1711.0,53.0,167.0,0.0,3.0,15543.0,...,19.0,47.0,454.0,0.0,600.0,35.0,1.0,588.0,332.0,227.0
272,2020-09-28,998983,1453.0,377.0,1714.0,53.0,171.0,0.0,3.0,15749.0,...,19.0,47.0,460.0,0.0,606.0,35.0,1.0,588.0,332.0,227.0
273,2020-09-29,1002903,1456.0,380.0,1719.0,53.0,176.0,0.0,3.0,16113.0,...,20.0,47.0,463.0,0.0,614.0,35.0,1.0,588.0,332.0,228.0
274,2020-09-30,1009109,1458.0,384.0,1726.0,53.0,179.0,0.0,3.0,16519.0,...,20.0,48.0,468.0,0.0,621.0,35.0,1.0,588.0,332.0,228.0
275,2020-10-01,1015043,1458.0,387.0,1734.0,53.0,182.0,0.0,3.0,16937.0,...,20.0,48.0,471.0,0.0,628.0,35.0,1.0,588.0,332.0,228.0